#!/bin/bash
# Setup Anthropic API Key for knowledge graph extraction

echo "Setting up Anthropic API Key..."
echo ""
echo "You have two options:"
echo ""
echo "1. Set environment variable (temporary, current session only):"
echo "   export ANTHROPIC_API_KEY='your-api-key-here'"
echo ""
echo "2. Create persistent config file:"
echo "   mkdir -p ~/.anthropic"
echo "   echo 'your-api-key-here' > ~/.anthropic/api_key"
echo ""
echo "To get your API key:"
echo "  1. Go to https://console.anthropic.com/settings/keys"
echo "  2. Create a new API key if you don't have one"
echo "  3. Copy the key and use one of the methods above"
echo ""
echo "Note: For this session, you can temporarily set it by running:"
echo ""
echo "  export ANTHROPIC_API_KEY='your-key'"
echo "  python3 scripts/build_knowledge_graph.py --test"
echo ""
